databaseChangeLog:
  - changeSet:
      id: 1
      author: kbojchevski
      changes:
        - createSequence:
            sequenceName: product_id_sequence
            incrementBy: 1
            startValue: 1000

  - changeSet:
      id: 2
      author: kbojchevski
      changes:
        - createTable:
            tableName: products
            columns:
              - column:
                  name: id
                  type: bigint
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    primaryKeyName: product_id_pk
                    nullable: false
              - column:
                  name: name
                  type: varchar(255)
                  constraints:
                    nullable: false
              - column:
                  name: description
                  type: varchar(255)
                  constraints:
                    nullable: false
              - column:
                  name: price
                  type: decimal(10,2)
                  constraints:
                    nullable: false
